layout_spectrum: 0.01699247
typography_spectrum: 0.02911267
color:
  saturation: 0.8286412
  lightness: 0.8804316
  brandStrength: 0.02624664
  rhythmicContrast: 0.2048069
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Digiversum
